### ISSUE TITLE
Make yum/vim available

### ISSUE THREAD

**Issue by mmoayyed** [UniconLabs/grouper-demo-docker#7]

**Comment by dima767** [comment]
`alias yum='sudo apt-get` ? It's an image based on Ubuntu (Debian), and so `apt-get` is already available. No?

**Comment by mmoayyed** [comment]
Sure, that will work. What I am more after is, the following story:

I launch into the image and I can immediately do "vim x". That's as simple as I want it.

**Comment by dima767** [comment]
Change the title then to "Make vim available..." ;-)

**Comment by jtgasper3** [comment]
That's do able. I'm actually going to add Thompson's groovy grouper shell as well.

**Comment by mmoayyed** [comment]
Awesome. All hail @wgthom

**Comment by jtgasper3** [comment]
See https://github.com/UniconLabs/grouper-demo-docker/pull/8

Vim will be available in today's build, Tag: `08-31-2015`
